### ISSUE TITLE
Редірект

### ISSUE THREAD

**Issue by volia-29** [Ighoorr/Coffee#1]
https://github.com/Ighoorr/Coffee/blob/25ca7bcf5682c1934d5b3063de2e53dfbcda10ca/Task2%20UI/WebApp/WebApp/Views/Users/Index.cshtml#L12

А в тебе тут спрацьовує редірект? 
Бо в мене він не заходить, якщо не додати атрибут HttpGet до методу Create:
[HttpGet("Create")]
public IActionResult Create()

**Comment by Ighoorr** [comment]
Виправив (можливо забув вернути після змін),
Я переніс ui на реакт
